# Generated by Django 5.0.1 on 2024-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('City', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Post', models.CharField(max_length=150)),
                ('StartDate', models.DateField()),
            ],
        ),
    ]
