# Generated by Django 5.0.1 on 2024-02-15 11:05

import todolist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(upload_to='images/', validators=[todolist.models.validate_picture_extension]),
        ),
    ]
