# Generated by Django 5.0.1 on 2024-02-15 11:43

import django.core.validators
import todolist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Picture',
            field=models.ImageField(upload_to='images/', validators=[todolist.models.validate_picture_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
